const TAG = {
  TOKEN: {
    SIGN_IN: "TOKEN_SIGN_IN",
    SIGN_OUT: "TOKEN_SIGN_OUT",
  },

  LOADING: {
    TURN_ON: "LOADING_TURN_ON",
    TURN_OFF: "LOADING_TURN_OFF",
  },

  PROFILE: {
    SIGN_IN: "PROFILE_ON_SIGN_IN",
    SIGN_OUT: "PROFILE_ON_SIGN_OUT",
    UPDATE: "PROFILE_UPDATE",
  },

  CITY: {
    UPDATE: "CITY_UPDATE",
  },

  ADDRESS_DELIVERY: {
    UPDATE_ADDRESS: "ADDRESS_DELIVERY_UPDATE_ADDRESS",
    UPDATE_COORDINATE: "ADDRESS_DELIVERY_UPDATE_COORDINATE",
  },

  CART: {
    LOAD_FROM_LOCAL_STORAGE: "CART_LOAD_FROM_LOCAL_STORAGE",
    SAVE_CART_INTO_LOCAL_STORAGE: "CART_SAVE_CART_INTO_LOCAL_STORAGE",
    UPDATE_CART: "CART_UPDATE_CART",
  },

  INDEX_PROFILE: {
    UPDATE: "INDEX_PROFILE_UPDATE",
  },
};

export default TAG;
